enum ErrorTypes {
  PARAMETER_MISSING = 'PARAMETER_MISSING',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_DOES_NOT_EXISTS = 'USER_DOES_NOT_EXISTS',
  PASSWORD_IS_INCORRECT = 'PASSWORD_IS_INCORRECT',
  UNAUTHORIAZTION = 'UNAUTHORIAZTION',
  UNPERMISSION = 'UNPERMISSION',
  DOES_NOT_VOLUNTEER = 'DOES_NOT_VOLUNTEER',
  NOT_ENOUGH_POINTS = 'NOT_ENOUGH_POINTS',
  NOT_ENOUGH_EXCHANGEITEM = 'NOT_ENOUGH_EXCHANGEITEM',
  DOES_NOT_DOCTOR = 'DOES_NOT_DOCTOR'
}

export default ErrorTypes
