const PARAMETER_MISSING = 'PARAMETER_MISSING'
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
const USER_DOES_NOT_EXISTS = 'USER_DOES_NOT_EXISTS'
const PASSWORD_IS_INCORRECT = 'PASSWORD_IS_INCORRECT'
const UNAUTHORIAZTION = 'UNAUTHORIAZTION'
const UNPERMISSION = 'UNPERMISSION'
const DOES_NOT_VOLUNTEER = 'DOES_NOT_VOLUNTEER'
const NOT_ENOUGH_POINTS = 'NOT_ENOUGH_POINTS'
const NOT_ENOUGH_EXCHANGEITEM = 'NOT_ENOUGH_EXCHANGEITEM'
const DOES_NOT_DOCTOR = 'DOES_NOT_DOCTOR'

module.exports = {
    PARAMETER_MISSING,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXISTS,
    PASSWORD_IS_INCORRECT,
    UNAUTHORIAZTION,
    UNPERMISSION,
    DOES_NOT_VOLUNTEER,
    NOT_ENOUGH_POINTS,
    NOT_ENOUGH_EXCHANGEITEM,
    DOES_NOT_DOCTOR
}
