const PARAMETER_MISSING = 'PARAMETER_MISSING'
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
const USER_DOES_NOT_EXISTS = 'USER_DOES_NOT_EXISTS'
const PASSWORD_IS_INCORRECT = 'PASSWORD_IS_INCORRECT'
const UNAUTHORIAZTION = 'UNAUTHORIAZTION'
const UNPERMISSION = 'UNPERMISSION'

module.exports = {
    PARAMETER_MISSING,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXISTS,
    PASSWORD_IS_INCORRECT,
    UNAUTHORIAZTION,
    UNPERMISSION
}
